/** Known HQ cities for Canadian institutions — sourced from official websites / directories */
export const KNOWN_INSTITUTION_CITIES: Record<string, string> = {
  "univcan:university-of-alberta": "Edmonton",
  "univcan:university-of-calgary": "Calgary",
  "univcan:university-of-lethbridge": "Lethbridge",
  "univcan:athabasca-university": "Athabasca",
  "univcan:concordia-university-of-edmonton": "Edmonton",
  "univcan:mount-royal-university": "Calgary",
  "univcan:university-of-british-columbia": "Vancouver",
  "univcan:simon-fraser-university": "Burnaby",
  "univcan:university-of-victoria": "Victoria",
  "univcan:university-of-northern-british-columbia": "Prince George",
  "univcan:trinity-western-university": "Langley",
  "univcan:emily-carr-university-of-art-design": "Vancouver",
  "univcan:university-of-manitoba": "Winnipeg",
  "univcan:university-of-winnipeg": "Winnipeg",
  "univcan:brandon-university": "Brandon",
  "univcan:universite-de-saint-boniface": "Winnipeg",
  "univcan:university-of-new-brunswick": "Fredericton",
  "univcan:mount-allison-university": "Sackville",
  "univcan:st-thomas-university": "Fredericton",
  "univcan:universite-de-moncton": "Moncton",
  "univcan:memorial-university-of-newfoundland-and-labrador": "St. John's",
  "univcan:mcmaster-university": "Hamilton",
  "univcan:queens-university": "Kingston",
  "univcan:university-of-guelph": "Guelph",
  "univcan:university-of-ottawa": "Ottawa",
  "univcan:university-of-waterloo": "Waterloo",
  "univcan:university-of-windsor": "Windsor",
  "univcan:wilfrid-laurier-university": "Waterloo",
  "univcan:mcgill-university": "Montreal",
  "univcan:universite-de-montreal": "Montreal",
  "univcan:universite-laval": "Quebec City",
  "univcan:universite-de-sherbrooke": "Sherbrooke",
  "univcan:university-of-prince-edward-island": "Charlottetown",
  "univcan:university-of-regina": "Regina",
  "univcan:university-of-saskatchewan": "Saskatoon",
  "univcan:yukon-university": "Whitehorse",
  "univcan:brock-university": "St. Catharines",
  "univcan:algoma-university": "Sault Ste. Marie",
  "univcan:ontario-tech-university": "Oshawa",
  "univcan:cape-breton-university": "Sydney",
  "univcan:mount-saint-vincent-university": "Halifax",
  "univcan:universite-sainte-anne": "Church Point",
  "cican:red-river-college-polytechnic": "Winnipeg",
  "cican:sait": "Calgary",
  "cican:lethbridge-polytechnic": "Lethbridge",
  "cican:norquest-college": "Edmonton",
  "cican:red-deer-polytechnic": "Red Deer",
  "cican:algonquin-college": "Ottawa",
  "cican:centennial-college": "Toronto",
  "cican:humber-college": "Toronto",
  "cican:seneca-polytechnic": "Toronto",
  "cican:george-brown-college": "Toronto",
  "cican:okanagan-college": "Kelowna",
  "cican:selkirk-college": "Castlegar",
  "cican:nova-scotia-community-college": "Halifax",
  "cican:college-of-the-north-atlantic": "Stephenville",
};

export function resolveKnownCity(externalId: string): string | null {
  return KNOWN_INSTITUTION_CITIES[externalId] ?? null;
}
