/**
 * Comprehensive undergraduate fields of study common in Nigeria (NUC/JAMB-style
 * programmes) plus standard international names. Merged with catalog fields at runtime.
 */
export const FIELDS_OF_STUDY = [
  // Medicine & health
  "Medicine and Surgery (MBBS)",
  "Nursing Science",
  "Pharmacy",
  "Dentistry",
  "Medical Laboratory Science",
  "Physiotherapy",
  "Radiography",
  "Public Health",
  "Anatomy",
  "Physiology",
  "Optometry",
  "Veterinary Medicine",
  "Health Information Management",
  "Environmental Health Science",
  "Human Nutrition and Dietetics",
  "Medical Rehabilitation",

  // Biological & life sciences
  "Microbiology",
  "Biochemistry",
  "Biology",
  "Molecular Biology",
  "Biotechnology",
  "Genetics",
  "Immunology",
  "Zoology",
  "Botany",
  "Marine Biology",
  "Parasitology and Entomology",
  "Applied Biology",
  "Biomedical Science",
  "Food Science and Technology",
  "Food Microbiology",
  "Nutrition and Dietetics",
  "Fisheries",
  "Forestry and Wildlife",
  "Environmental Biology",
  "Environmental Management",

  // Physical sciences
  "Chemistry",
  "Industrial Chemistry",
  "Pure and Applied Chemistry",
  "Physics",
  "Applied Physics",
  "Mathematics",
  "Statistics",
  "Computer Science",
  "Geology",
  "Geophysics",
  "Meteorology",

  // Agriculture
  "Agriculture",
  "Agricultural Science",
  "Agricultural Economics",
  "Agricultural Extension",
  "Animal Science",
  "Crop Science",
  "Soil Science",
  "Agronomy",
  "Horticulture",
  "Agricultural Engineering",

  // Engineering
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Electrical and Electronics Engineering",
  "Electronic Engineering",
  "Chemical Engineering",
  "Petroleum Engineering",
  "Petrochemical Engineering",
  "Computer Engineering",
  "Systems Engineering",
  "Biomedical Engineering",
  "Metallurgical and Materials Engineering",
  "Industrial and Production Engineering",
  "Agricultural and Bio-Resources Engineering",
  "Mechatronics Engineering",
  "Telecommunications Engineering",
  "Marine Engineering",
  "Aeronautical Engineering",
  "Building Technology",
  "Architecture",
  "Quantity Surveying",
  "Urban and Regional Planning",
  "Estate Management",
  "Surveying and Geoinformatics",

  // Computing & IT
  "Software Engineering",
  "Information Technology",
  "Information Systems",
  "Cyber Security",
  "Data Science",
  "Artificial Intelligence",
  "Information and Communication Technology",
  "Library and Information Science",

  // Business & economics
  "Accounting",
  "Business Administration",
  "Business Management",
  "Economics",
  "Finance",
  "Banking and Finance",
  "Marketing",
  "Entrepreneurship",
  "Insurance",
  "Actuarial Science",
  "Human Resource Management",
  "Public Administration",
  "Transport Management",
  "Hospitality and Tourism Management",
  "Office Technology and Management",

  // Social sciences
  "Political Science",
  "Sociology",
  "Psychology",
  "International Relations",
  "Geography",
  "Demography and Social Statistics",
  "Criminology and Security Studies",
  "Peace and Conflict Studies",
  "Social Work",

  // Arts & humanities
  "Mass Communication",
  "English Language",
  "English and Literary Studies",
  "Linguistics",
  "French",
  "Arabic Studies",
  "History and International Studies",
  "Philosophy",
  "Religious Studies",
  "Theatre Arts",
  "Music",
  "Fine and Applied Arts",
  "Creative Arts",

  // Law
  "Law",

  // Education
  "Education",
  "Adult Education",
  "Guidance and Counselling",
  "Educational Management",
  "Science Education",
  "Arts Education",
  "Social Science Education",
  "Technical Education",
  "Early Childhood Education",

  // Other professional
  "Library Science",
  "Industrial Relations and Personnel Management",
  "Project Management",
  "Logistics and Supply Chain Management",
  "Real Estate Management",
  "Taxation",
] as const;

/**
 * Common Nigerian undergraduate courses (for relevant-courses chips / suggestions).
 */
export const UNDERGRADUATE_COURSE_SUGGESTIONS = [
  // Sciences
  "Biochemistry",
  "Cell Biology",
  "Molecular Biology",
  "Microbiology",
  "Genetics",
  "Immunology",
  "Parasitology",
  "Virology",
  "Mycology",
  "Organic Chemistry",
  "Inorganic Chemistry",
  "Physical Chemistry",
  "Analytical Chemistry",
  "Physics",
  "Mathematics",
  "Statistics",
  "Calculus",
  "Linear Algebra",
  "Research Methods",
  "Laboratory Techniques",

  // Medical / health sciences
  "Human Anatomy",
  "Human Physiology",
  "Pathology",
  "Pharmacology",
  "Medical Microbiology",
  "Clinical Biochemistry",
  "Epidemiology",
  "Community Health",
  "Public Health",

  // Engineering & computing
  "Computer Science",
  "Programming",
  "Data Structures",
  "Algorithms",
  "Database Systems",
  "Software Engineering",
  "Thermodynamics",
  "Fluid Mechanics",
  "Strength of Materials",
  "Circuit Theory",
  "Control Systems",
  "Digital Electronics",

  // Agriculture & environment
  "Crop Production",
  "Animal Production",
  "Soil Science",
  "Agricultural Economics",
  "Environmental Science",
  "Ecology",

  // Business & social sciences
  "Accounting",
  "Financial Accounting",
  "Management Accounting",
  "Economics",
  "Microeconomics",
  "Macroeconomics",
  "Business Law",
  "Corporate Finance",
  "Marketing",
  "Organizational Behaviour",
  "Political Science",
  "Sociology",
  "Psychology",
  "Research Methodology",
] as const;

export type FieldOfStudy = (typeof FIELDS_OF_STUDY)[number];
